
import lib.jdb.connection.JDBConnection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vmf
 */
public class JFrameMotoristas extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMotoristas
     */
    public JFrameMotoristas() {
        initComponents();
    }
    public JFrameMotoristas(JDBConnection jdb) {
        initComponents();
        jDBQueryMotorista.setJDBConnection(jdb);
        jDBQuerySlaveMotoristaContatos.setJDBConnection(jdb);
        jDBQuerySlaveMotoristaEndereco.setJDBConnection(jdb);
        jDBQueryMotorista.execQuery();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDBQuerySlaveMotoristaContatos = new lib.jdb.jdbquery.JDBQuerySlave();
        jDBQueryMotorista = new lib.jdb.jdbquery.JDBQuery();
        jDBControlStyle1 = new lib.jdb.control.jdbcontrolstyle.JDBControlStyle();
        jDBQuerySlaveMotoristaEndereco = new lib.jdb.jdbquery.JDBQuerySlave();
        jScrollPane3 = new javax.swing.JScrollPane();
        jDBTable3 = new lib.jdb.control.jdbtable.JDBTable();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jDBTextField13 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jDBTextField14 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel17 = new javax.swing.JLabel();
        jDBTextFieldSalarioBruto = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel19 = new javax.swing.JLabel();
        jDBButtonSave4 = new lib.jdb.control.jdbbuttonsave.JDBButtonSave();
        jDBButtonNew3 = new lib.jdb.control.jdbbuttonnew.JDBButtonNew();
        jLabelSalLiquido = new javax.swing.JLabel();
        jDBButtonDelete3 = new lib.jdb.control.jdbbuttondelete.JDBButtonDelete();
        jLabel3 = new javax.swing.JLabel();
        jDBTextField3 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel35 = new javax.swing.JLabel();
        jDBTextField26 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jDBTextField16 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel22 = new javax.swing.JLabel();
        jDBTextField17 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel23 = new javax.swing.JLabel();
        jDBTextField18 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jDBButtonSave5 = new lib.jdb.control.jdbbuttonsave.JDBButtonSave();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jDBTable4 = new lib.jdb.control.jdbtable.JDBTable();
        jLabel26 = new javax.swing.JLabel();
        jDBComboBox4 = new lib.jdb.control.jdbcombobox.JDBComboBox();
        jDBTextField21 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jDBButtonSave6 = new lib.jdb.control.jdbbuttonsave.JDBButtonSave();
        jDBButtonNew4 = new lib.jdb.control.jdbbuttonnew.JDBButtonNew();
        jDBButtonDelete2 = new lib.jdb.control.jdbbuttondelete.JDBButtonDelete();

        jDBQuerySlaveMotoristaContatos.setJDBQueryMaster(jDBQueryMotorista);
        jDBQuerySlaveMotoristaContatos.setSQL("select * from contato where id in( select contato_id from motorista_contatos where motorista_id = {$id})");
        jDBQuerySlaveMotoristaContatos.setMasterKeyField("id");
        jDBQuerySlaveMotoristaContatos.setSlaveForeignKeyField("id");
        jDBQuerySlaveMotoristaContatos.addInsertEventListener(new lib.jdb.jdbquery.event.InsertEventListener() {
            public void beforeInsert(lib.jdb.jdbquery.event.InsertEventObject evt) {
                jDBQuerySlaveMotoristaContatosBeforeInsert(evt);
            }
            public void afterInsert(lib.jdb.jdbquery.event.InsertEventObject evt) {
                jDBQuerySlaveMotoristaContatosAfterInsert(evt);
            }
        });

        jDBQueryMotorista.setSQL("select * from motorista");
        jDBQueryMotorista.addScrollEventListener(new lib.jdb.jdbquery.event.ScrollEventListener() {
            public void beforeScroll(lib.jdb.jdbquery.event.ScrollEventObject evt) {
            }
            public void afterScroll(lib.jdb.jdbquery.event.ScrollEventObject evt) {
                jDBQueryMotoristaAfterScroll(evt);
            }
        });

        jDBQuerySlaveMotoristaEndereco.setJDBQueryMaster(jDBQueryMotorista);
        jDBQuerySlaveMotoristaEndereco.setSQL("select * from endereco_motorista where motorista_id = {$id}");
        jDBQuerySlaveMotoristaEndereco.setMasterKeyField("id");
        jDBQuerySlaveMotoristaEndereco.setSaveManually(true);
        jDBQuerySlaveMotoristaEndereco.setSlaveForeignKeyField("motorista_id");
        jDBQuerySlaveMotoristaEndereco.addExecQueryEventListener(new lib.jdb.jdbquery.event.ExecQueryEventListener() {
            public void beforeExecQuery(lib.jdb.jdbquery.event.ExecQueryEventObject evt) {
            }
            public void afterExecQuery(lib.jdb.jdbquery.event.ExecQueryEventObject evt) {
                jDBQuerySlaveMotoristaEnderecoAfterExecQuery(evt);
            }
        });
        jDBQuerySlaveMotoristaEndereco.addSaveManuallyEventListener(new lib.jdb.jdbquery.event.SaveManuallyEventListener() {
            public void onSaveManually(lib.jdb.jdbquery.event.SaveManuallyEventObject evt) {
                jDBQuerySlaveMotoristaEnderecoOnSaveManually(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Motoristas");

        jDBTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jDBTable3.setJDBQuery(jDBQueryMotorista);
        jDBTable3.setEditable(false);
        jDBTable3.setInvisibleFields("id");
        jScrollPane3.setViewportView(jDBTable3);

        jLabel16.setText("Nome");

        jDBTextField13.setJDBQuery(jDBQueryMotorista);
        jDBTextField13.setFieldName("motorista");

        jDBTextField14.setJDBQuery(jDBQueryMotorista);
        jDBTextField14.setFieldName("cpf");

        jLabel17.setText("CPF");

        jDBTextFieldSalarioBruto.setJDBQuery(jDBQueryMotorista);
        jDBTextFieldSalarioBruto.setFieldName("salario");
        jDBTextFieldSalarioBruto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDBTextFieldSalarioBrutoKeyReleased(evt);
            }
        });

        jLabel19.setText("Salário Bruto");

        jDBButtonSave4.setJDBQuery(jDBQueryMotorista);

        jDBButtonNew3.setJDBQuery(jDBQueryMotorista);

        jLabelSalLiquido.setText("INSS R$ 0,00 + Salário Líquido R$ 0,00");

        jDBButtonDelete3.setJDBQuery(jDBQueryMotorista);

        jLabel3.setText("Dist. Trajeto");

        jDBTextField3.setJDBQuery(jDBQueryMotorista);
        jDBTextField3.setFieldName("distancia_trajeto");

        jLabel35.setText("Comb./Km");

        jDBTextField26.setJDBQuery(jDBQueryMotorista);
        jDBTextField26.setFieldName("litro_combustivel_por_km");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel19)
                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel35)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jDBTextFieldSalarioBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelSalLiquido, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDBTextField13, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .addComponent(jDBTextField14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(17, 17, 17))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jDBButtonDelete3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDBButtonNew3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDBButtonSave4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jDBTextField26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(jDBTextField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jDBTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jDBTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDBTextFieldSalarioBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jLabelSalLiquido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDBTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDBTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDBButtonSave4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDBButtonNew3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDBButtonDelete3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane3.addTab("Dados", jPanel9);

        jLabel21.setText("Rua");

        jDBTextField16.setJDBQuery(jDBQuerySlaveMotoristaEndereco);
        jDBTextField16.setFieldName("rua");

        jLabel22.setText("Num.");

        jDBTextField17.setJDBQuery(jDBQuerySlaveMotoristaEndereco);
        jDBTextField17.setFieldName("num");

        jLabel23.setText("Bairro");

        jDBTextField18.setJDBQuery(jDBQuerySlaveMotoristaEndereco);
        jDBTextField18.setFieldName("bairro");

        jDBButtonSave5.setJDBQuery(jDBQuerySlaveMotoristaEndereco);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(4, 4, 4)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDBTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDBTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 353, Short.MAX_VALUE)
                        .addComponent(jDBButtonSave5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jDBTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jDBTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jDBTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jDBTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jDBButtonSave5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Endereço", jPanel10);

        jDBTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jDBTable4.setJDBQuery(jDBQuerySlaveMotoristaContatos);
        jDBTable4.setInvisibleFields("id");
        jScrollPane4.setViewportView(jDBTable4);

        jLabel26.setText("Tipo");

        jDBComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Celular", "Email", "Telefone" }));
        jDBComboBox4.setJDBQuery(jDBQuerySlaveMotoristaContatos);
        jDBComboBox4.setFieldName("tipo");

        jDBTextField21.setJDBQuery(jDBQuerySlaveMotoristaContatos);
        jDBTextField21.setFieldName("contato");

        jDBButtonSave6.setJDBQuery(jDBQuerySlaveMotoristaContatos);

        jDBButtonNew4.setJDBQuery(jDBQuerySlaveMotoristaContatos);

        jDBButtonDelete2.setJDBQuery(jDBQuerySlaveMotoristaContatos);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDBComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDBTextField21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jDBButtonDelete2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDBButtonNew4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDBButtonSave6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jDBComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDBTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDBButtonSave6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDBButtonNew4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDBButtonDelete2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane3.addTab("Contatos", jPanel11);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane3)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDBTextFieldSalarioBrutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDBTextFieldSalarioBrutoKeyReleased
        calcInss();
    }//GEN-LAST:event_jDBTextFieldSalarioBrutoKeyReleased

    private void jDBQuerySlaveMotoristaContatosBeforeInsert(lib.jdb.jdbquery.event.InsertEventObject evt) {//GEN-FIRST:event_jDBQuerySlaveMotoristaContatosBeforeInsert
        jDBQuerySlaveMotoristaContatos.setNewCurrentFieldValue("id", null);
    }//GEN-LAST:event_jDBQuerySlaveMotoristaContatosBeforeInsert

    private void jDBQuerySlaveMotoristaContatosAfterInsert(lib.jdb.jdbquery.event.InsertEventObject evt) {//GEN-FIRST:event_jDBQuerySlaveMotoristaContatosAfterInsert
      /*  jDBUpdateTransaction1.setSQL("insert into motorista_contatos values("+
            jDBQueryMotorista.getCurrentFieldValue("id") +","+
            jDBQuerySlaveMotoristaContatos.getCurrentFieldValue("id")+")");
        try {
            jDBUpdateTransaction1.execUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_jDBQuerySlaveMotoristaContatosAfterInsert

     private void calcInss() {
        if(jDBTextFieldSalarioBruto.getText().length() > 0){
            float sal = Float.parseFloat(jDBTextFieldSalarioBruto.getText().replace(",", "."));
            jLabelSalLiquido.setText(String.format("INSS R$ %.2f + Salário Líquido R$ %.2f", 
                    sal*0.1015,sal-(sal*0.1015)));
        }
    }
     
    private void jDBQueryMotoristaAfterScroll(lib.jdb.jdbquery.event.ScrollEventObject evt) {//GEN-FIRST:event_jDBQueryMotoristaAfterScroll
        calcInss();
    }//GEN-LAST:event_jDBQueryMotoristaAfterScroll

    private void jDBQuerySlaveMotoristaEnderecoAfterExecQuery(lib.jdb.jdbquery.event.ExecQueryEventObject evt) {//GEN-FIRST:event_jDBQuerySlaveMotoristaEnderecoAfterExecQuery
        if(jDBQuerySlaveMotoristaEndereco.getRow() < 1){
            jDBQuerySlaveMotoristaEndereco.insert();
        }
    }//GEN-LAST:event_jDBQuerySlaveMotoristaEnderecoAfterExecQuery

    private void jDBQuerySlaveMotoristaEnderecoOnSaveManually(lib.jdb.jdbquery.event.SaveManuallyEventObject evt) {//GEN-FIRST:event_jDBQuerySlaveMotoristaEnderecoOnSaveManually
        jDBQuerySlaveMotoristaEndereco.save();
    }//GEN-LAST:event_jDBQuerySlaveMotoristaEnderecoOnSaveManually

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMotoristas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMotoristas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMotoristas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMotoristas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMotoristas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lib.jdb.control.jdbbuttondelete.JDBButtonDelete jDBButtonDelete2;
    private lib.jdb.control.jdbbuttondelete.JDBButtonDelete jDBButtonDelete3;
    private lib.jdb.control.jdbbuttonnew.JDBButtonNew jDBButtonNew3;
    private lib.jdb.control.jdbbuttonnew.JDBButtonNew jDBButtonNew4;
    private lib.jdb.control.jdbbuttonsave.JDBButtonSave jDBButtonSave4;
    private lib.jdb.control.jdbbuttonsave.JDBButtonSave jDBButtonSave5;
    private lib.jdb.control.jdbbuttonsave.JDBButtonSave jDBButtonSave6;
    private lib.jdb.control.jdbcombobox.JDBComboBox jDBComboBox4;
    private lib.jdb.control.jdbcontrolstyle.JDBControlStyle jDBControlStyle1;
    private lib.jdb.jdbquery.JDBQuery jDBQueryMotorista;
    private lib.jdb.jdbquery.JDBQuerySlave jDBQuerySlaveMotoristaContatos;
    private lib.jdb.jdbquery.JDBQuerySlave jDBQuerySlaveMotoristaEndereco;
    private lib.jdb.control.jdbtable.JDBTable jDBTable3;
    private lib.jdb.control.jdbtable.JDBTable jDBTable4;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField13;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField14;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField16;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField17;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField18;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField21;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField26;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField3;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextFieldSalarioBruto;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabelSalLiquido;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane3;
    // End of variables declaration//GEN-END:variables
}
