
import lib.jdb.connection.JDBConnection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vmf
 */
public class JFramePassageiros extends javax.swing.JFrame {
        String SQLPassageiros = "select  * from passageiro ";

    /**
     * Creates new form JFramePassageiros
     */
    public JFramePassageiros() {
        initComponents();
    }
    public JFramePassageiros(JFramePrincipal jfP) {
        initComponents();
        this.jDBQueryPassageiros.setJDBConnection(jfP.getJDBConnection());
        this.jDBQueryCursos.setJDBConnection(jfP.getJDBConnection());
        this.jDBQuerySlavePassageiroContatos.setJDBConnection(jfP.getJDBConnection());
        this.jDBQuerySlavePassageiroEndereco.setJDBConnection(jfP.getJDBConnection());
        this.jDBQuerySlavePassageiroMensalidades.setJDBConnection(jfP.getJDBConnection());
        this.jDBQueryPassageiros.execQuery();
    }
    public JFramePassageiros(JFramePrincipal jfP,int passageiroId) {
        initComponents();
        this.jDBQueryPassageiros.setJDBConnection(jfP.getJDBConnection());
        this.jDBQueryCursos.setJDBConnection(jfP.getJDBConnection());
        this.jDBQuerySlavePassageiroContatos.setJDBConnection(jfP.getJDBConnection());
        this.jDBQuerySlavePassageiroEndereco.setJDBConnection(jfP.getJDBConnection());
        this.jDBQuerySlavePassageiroMensalidades.setJDBConnection(jfP.getJDBConnection());
        this.jDBQueryPassageiros.execQuery();
        this.jDBQueryPassageiros.locate("id", Integer.toString(passageiroId), false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDBQueryPassageiros = new lib.jdb.jdbquery.JDBQuery();
        jDBQuerySlavePassageiroMensalidades = new lib.jdb.jdbquery.JDBQuerySlave();
        jDBQuerySlavePassageiroContatos = new lib.jdb.jdbquery.JDBQuerySlave();
        jDBQuerySlavePassageiroEndereco = new lib.jdb.jdbquery.JDBQuerySlave();
        jDBQueryCursos = new lib.jdb.jdbquery.JDBQuery();
        jDBControlStyle1 = new lib.jdb.control.jdbcontrolstyle.JDBControlStyle();
        jTextFieldBuscapassageiroNome = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jDBTextField9 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jDBTextField10 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel11 = new javax.swing.JLabel();
        jDBLookUpComboBox1 = new lib.jdb.control.jdblookupcombobox.JDBLookUpComboBox();
        jLabel12 = new javax.swing.JLabel();
        jDBTextField11 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel13 = new javax.swing.JLabel();
        jDBComboBox1 = new lib.jdb.control.jdbcombobox.JDBComboBox();
        jLabel14 = new javax.swing.JLabel();
        jDBButtonSave2 = new lib.jdb.control.jdbbuttonsave.JDBButtonSave();
        jDBButtonNew1 = new lib.jdb.control.jdbbuttonnew.JDBButtonNew();
        jDBButtonDelete4 = new lib.jdb.control.jdbbuttondelete.JDBButtonDelete();
        jDBCheckBox1 = new lib.jdb.control.jdbcheckbox.JDBCheckBox();
        jDBCheckBox2 = new lib.jdb.control.jdbcheckbox.JDBCheckBox();
        jLabel16 = new javax.swing.JLabel();
        jDBTextArea1 = new lib.jdb.control.jdbtextarea.JDBTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jDBTextField4 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel6 = new javax.swing.JLabel();
        jDBTextField5 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel7 = new javax.swing.JLabel();
        jDBTextField6 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jDBButtonSave1 = new lib.jdb.control.jdbbuttonsave.JDBButtonSave();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jDBTable2 = new lib.jdb.control.jdbtable.JDBTable();
        jLabel15 = new javax.swing.JLabel();
        jDBComboBox2 = new lib.jdb.control.jdbcombobox.JDBComboBox();
        jDBTextField12 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jDBButtonSave3 = new lib.jdb.control.jdbbuttonsave.JDBButtonSave();
        jDBButtonNew2 = new lib.jdb.control.jdbbuttonnew.JDBButtonNew();
        jDBButtonDelete1 = new lib.jdb.control.jdbbuttondelete.JDBButtonDelete();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jDBTable5 = new lib.jdb.control.jdbtable.JDBTable();
        jButtonPagar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDBTable1 = new lib.jdb.control.jdbtable.JDBTable();

        jDBQueryPassageiros.setSQL("select  * from passageiro \n");

        jDBQuerySlavePassageiroMensalidades.setJDBQueryMaster(jDBQueryPassageiros);
        jDBQuerySlavePassageiroMensalidades.setSQL("select * from mensalidade where passageiro_id = {$id}");
        jDBQuerySlavePassageiroMensalidades.setMasterKeyField("id");
        jDBQuerySlavePassageiroMensalidades.setSlaveForeignKeyField("passageiro_id");

        jDBQuerySlavePassageiroContatos.setJDBQueryMaster(jDBQueryPassageiros);
        jDBQuerySlavePassageiroContatos.setSQL("select * from contato where id in( select contato_id from passageiro_contatos where passageiro_id = {$id})");
        jDBQuerySlavePassageiroContatos.setMasterKeyField("id");
        jDBQuerySlavePassageiroContatos.setSlaveForeignKeyField("id");
        jDBQuerySlavePassageiroContatos.addInsertEventListener(new lib.jdb.jdbquery.event.InsertEventListener() {
            public void beforeInsert(lib.jdb.jdbquery.event.InsertEventObject evt) {
                jDBQuerySlavePassageiroContatosBeforeInsert(evt);
            }
            public void afterInsert(lib.jdb.jdbquery.event.InsertEventObject evt) {
                jDBQuerySlavePassageiroContatosAfterInsert(evt);
            }
        });

        jDBQuerySlavePassageiroEndereco.setJDBQueryMaster(jDBQueryPassageiros);
        jDBQuerySlavePassageiroEndereco.setSQL("select * from endereco_passageiro where passageiro_id =  {$id}");
        jDBQuerySlavePassageiroEndereco.setMasterKeyField("id");
        jDBQuerySlavePassageiroEndereco.setSaveManually(true);
        jDBQuerySlavePassageiroEndereco.setSlaveForeignKeyField("passageiro_id");
        jDBQuerySlavePassageiroEndereco.addExecQueryEventListener(new lib.jdb.jdbquery.event.ExecQueryEventListener() {
            public void beforeExecQuery(lib.jdb.jdbquery.event.ExecQueryEventObject evt) {
            }
            public void afterExecQuery(lib.jdb.jdbquery.event.ExecQueryEventObject evt) {
                jDBQuerySlavePassageiroEnderecoAfterExecQuery(evt);
            }
        });
        jDBQuerySlavePassageiroEndereco.addSaveManuallyEventListener(new lib.jdb.jdbquery.event.SaveManuallyEventListener() {
            public void onSaveManually(lib.jdb.jdbquery.event.SaveManuallyEventObject evt) {
                jDBQuerySlavePassageiroEnderecoOnSaveManually(evt);
            }
        });

        jDBQueryCursos.setSQL("select * from curso");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Passageiros");

        jTextFieldBuscapassageiroNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBuscapassageiroNomeKeyReleased(evt);
            }
        });

        jLabel9.setText("Nome");

        jButton1.setText("Relatorio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Nome");

        jDBTextField9.setJDBQuery(jDBQueryPassageiros);
        jDBTextField9.setFieldName("nome_completo");
        jDBTextField9.setjDBControlStyle(jDBControlStyle1);

        jDBTextField10.setJDBQuery(jDBQueryPassageiros);
        jDBTextField10.setFieldName("cpf");
        jDBTextField10.setjDBControlStyle(jDBControlStyle1);

        jLabel11.setText("CPF");

        jDBLookUpComboBox1.setJDBListQuery(jDBQueryCursos);
        jDBLookUpComboBox1.setJDBQuery(jDBQueryPassageiros);
        jDBLookUpComboBox1.setInvisibleFields("id total_semestres");
        jDBLookUpComboBox1.setjDBControlStyle(jDBControlStyle1);
        jDBLookUpComboBox1.setKeyField("curso_id");
        jDBLookUpComboBox1.setKeyListField("id");

        jLabel12.setText("Curso");

        jDBTextField11.setJDBQuery(jDBQueryPassageiros);
        jDBTextField11.setFieldName("semestre");
        jDBTextField11.setjDBControlStyle(jDBControlStyle1);

        jLabel13.setText("Semestre");

        jDBComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "S", "A", "B", "C", "D" }));
        jDBComboBox1.setJDBQuery(jDBQueryPassageiros);
        jDBComboBox1.setFieldName("classificacao");
        jDBComboBox1.setjDBControlStyle(jDBControlStyle1);

        jLabel14.setText("Classificação");

        jDBButtonSave2.setJDBQuery(jDBQueryPassageiros);

        jDBButtonNew1.setJDBQuery(jDBQueryPassageiros);

        jDBButtonDelete4.setJDBQuery(jDBQueryPassageiros);

        jDBCheckBox1.setJDBQuery(jDBQueryPassageiros);
        jDBCheckBox1.setFieldName("vai");
        jDBCheckBox1.setText("Vai");

        jDBCheckBox2.setJDBQuery(jDBQueryPassageiros);
        jDBCheckBox2.setFieldName("volta");
        jDBCheckBox2.setText("Volta");

        jLabel16.setText("Observações");

        jDBTextArea1.setJDBQuery(jDBQueryPassageiros);
        jDBTextArea1.setFieldName("obs");
        jDBTextArea1.setjDBControlStyle(jDBControlStyle1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 410, Short.MAX_VALUE)
                        .addComponent(jDBButtonDelete4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDBButtonNew1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDBButtonSave2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addComponent(jLabel12))
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jDBTextField10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDBLookUpComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDBComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDBTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jDBTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jDBCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDBCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jDBTextArea1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jDBTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jDBTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jDBComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDBLookUpComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jDBTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDBCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDBCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jDBTextArea1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDBButtonSave2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDBButtonNew1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDBButtonDelete4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Dados", jPanel8);

        jLabel5.setText("Rua");

        jDBTextField4.setJDBQuery(jDBQuerySlavePassageiroEndereco);
        jDBTextField4.setFieldName("rua");
        jDBTextField4.setjDBControlStyle(jDBControlStyle1);

        jLabel6.setText("Num.");

        jDBTextField5.setJDBQuery(jDBQuerySlavePassageiroEndereco);
        jDBTextField5.setFieldName("num");
        jDBTextField5.setjDBControlStyle(jDBControlStyle1);

        jLabel7.setText("Bairro");

        jDBTextField6.setJDBQuery(jDBQuerySlavePassageiroEndereco);
        jDBTextField6.setFieldName("bairro");
        jDBTextField6.setjDBControlStyle(jDBControlStyle1);

        jDBButtonSave1.setJDBQuery(jDBQuerySlavePassageiroEndereco);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDBTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(jDBTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDBTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE)
                .addComponent(jDBButtonSave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jDBTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jDBTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jDBTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jDBButtonSave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Endereço", jPanel4);

        jDBTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jDBTable2.setJDBQuery(jDBQuerySlavePassageiroContatos);
        jDBTable2.setInvisibleFields("id");
        jScrollPane2.setViewportView(jDBTable2);

        jLabel15.setText("Tipo");

        jDBComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Celular", "Email", "Telefone" }));
        jDBComboBox2.setJDBQuery(jDBQuerySlavePassageiroContatos);
        jDBComboBox2.setFieldName("tipo");
        jDBComboBox2.setjDBControlStyle(jDBControlStyle1);

        jDBTextField12.setJDBQuery(jDBQuerySlavePassageiroContatos);
        jDBTextField12.setFieldName("contato");
        jDBTextField12.setjDBControlStyle(jDBControlStyle1);

        jDBButtonSave3.setJDBQuery(jDBQuerySlavePassageiroContatos);

        jDBButtonNew2.setJDBQuery(jDBQuerySlavePassageiroContatos);

        jDBButtonDelete1.setJDBQuery(jDBQuerySlavePassageiroContatos);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDBComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDBTextField12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jDBButtonDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDBButtonNew2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDBButtonSave3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jDBComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDBTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDBButtonSave3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDBButtonNew2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDBButtonDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        jTabbedPane2.addTab("Contatos", jPanel6);

        jDBTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jDBTable5.setJDBQuery(jDBQuerySlavePassageiroMensalidades);
        jDBTable5.setInvisibleFields("passageiro_id");
        jScrollPane5.setViewportView(jDBTable5);

        jButtonPagar.setText("Pagar");
        jButtonPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonPagar)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jButtonPagar)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Mensalidades", jPanel7);

        jDBTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jDBTable1.setJDBQuery(jDBQueryPassageiros);
        jDBTable1.setCheckBoxIntoBooleanFields(true);
        jDBTable1.setClickOnColumnsToSort(true);
        jDBTable1.setEditable(false);
        jDBTable1.setInvisibleFields("id curso_id");
        jScrollPane1.setViewportView(jDBTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBuscapassageiroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldBuscapassageiroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagarActionPerformed
       // jDBQueryMensallidade.locate("id", jDBQuerySlavePassageiroMensalidades.getCurrentFieldValue("id"),true);
       // jTabbedPane1.setSelectedIndex(0);
       // jTabbedPane5.setSelectedIndex(1);
    }//GEN-LAST:event_jButtonPagarActionPerformed

    private void jTextFieldBuscapassageiroNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscapassageiroNomeKeyReleased
        jDBQueryPassageiros.setSQL(SQLPassageiros+ "where nome_completo like \"%"+
            jTextFieldBuscapassageiroNome.getText() + "%\" order by nome_completo");
        jDBQueryPassageiros.execQuery();
    }//GEN-LAST:event_jTextFieldBuscapassageiroNomeKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      //  geraRelatorio();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jDBQuerySlavePassageiroContatosBeforeInsert(lib.jdb.jdbquery.event.InsertEventObject evt) {//GEN-FIRST:event_jDBQuerySlavePassageiroContatosBeforeInsert
        jDBQuerySlavePassageiroContatos.setNewCurrentFieldValue("id", null);
    }//GEN-LAST:event_jDBQuerySlavePassageiroContatosBeforeInsert

    private void jDBQuerySlavePassageiroContatosAfterInsert(lib.jdb.jdbquery.event.InsertEventObject evt) {//GEN-FIRST:event_jDBQuerySlavePassageiroContatosAfterInsert
     /*   jDBUpdateTransaction1.setSQL("insert into passageiro_contatos values("+
            jDBQueryPassageiros.getCurrentFieldValue("id") +","+
            jDBQuerySlavePassageiroContatos.getCurrentFieldValue("id")+")");
        try {
            jDBUpdateTransaction1.execUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_jDBQuerySlavePassageiroContatosAfterInsert

    private void jDBQuerySlavePassageiroEnderecoAfterExecQuery(lib.jdb.jdbquery.event.ExecQueryEventObject evt) {//GEN-FIRST:event_jDBQuerySlavePassageiroEnderecoAfterExecQuery
        if(jDBQuerySlavePassageiroEndereco.getRow() < 1){
            jDBQuerySlavePassageiroEndereco.insert();
        }
    }//GEN-LAST:event_jDBQuerySlavePassageiroEnderecoAfterExecQuery

    private void jDBQuerySlavePassageiroEnderecoOnSaveManually(lib.jdb.jdbquery.event.SaveManuallyEventObject evt) {//GEN-FIRST:event_jDBQuerySlavePassageiroEnderecoOnSaveManually
        if(jDBQueryPassageiros.getCurrentFieldValueAsInteger("id") != null){
            jDBQuerySlavePassageiroEndereco.save();
        }
    }//GEN-LAST:event_jDBQuerySlavePassageiroEnderecoOnSaveManually

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePassageiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePassageiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePassageiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePassageiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePassageiros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonPagar;
    private lib.jdb.control.jdbbuttondelete.JDBButtonDelete jDBButtonDelete1;
    private lib.jdb.control.jdbbuttondelete.JDBButtonDelete jDBButtonDelete4;
    private lib.jdb.control.jdbbuttonnew.JDBButtonNew jDBButtonNew1;
    private lib.jdb.control.jdbbuttonnew.JDBButtonNew jDBButtonNew2;
    private lib.jdb.control.jdbbuttonsave.JDBButtonSave jDBButtonSave1;
    private lib.jdb.control.jdbbuttonsave.JDBButtonSave jDBButtonSave2;
    private lib.jdb.control.jdbbuttonsave.JDBButtonSave jDBButtonSave3;
    private lib.jdb.control.jdbcheckbox.JDBCheckBox jDBCheckBox1;
    private lib.jdb.control.jdbcheckbox.JDBCheckBox jDBCheckBox2;
    private lib.jdb.control.jdbcombobox.JDBComboBox jDBComboBox1;
    private lib.jdb.control.jdbcombobox.JDBComboBox jDBComboBox2;
    private lib.jdb.control.jdbcontrolstyle.JDBControlStyle jDBControlStyle1;
    private lib.jdb.control.jdblookupcombobox.JDBLookUpComboBox jDBLookUpComboBox1;
    private lib.jdb.jdbquery.JDBQuery jDBQueryCursos;
    private lib.jdb.jdbquery.JDBQuery jDBQueryPassageiros;
    private lib.jdb.jdbquery.JDBQuerySlave jDBQuerySlavePassageiroContatos;
    private lib.jdb.jdbquery.JDBQuerySlave jDBQuerySlavePassageiroEndereco;
    private lib.jdb.jdbquery.JDBQuerySlave jDBQuerySlavePassageiroMensalidades;
    private lib.jdb.control.jdbtable.JDBTable jDBTable1;
    private lib.jdb.control.jdbtable.JDBTable jDBTable2;
    private lib.jdb.control.jdbtable.JDBTable jDBTable5;
    private lib.jdb.control.jdbtextarea.JDBTextArea jDBTextArea1;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField10;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField11;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField12;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField4;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField5;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField6;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextFieldBuscapassageiroNome;
    // End of variables declaration//GEN-END:variables
}
