
import lib.jdb.connection.JDBConnection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vmf
 */
public class JFrameMensalidades extends javax.swing.JFrame {
    String SQLMensalidade = "select * from mensalidade where 1=1 ";
    JFramePrincipal jfP=null;
    /**
     * Creates new form JFrameMensalidades
     */
    public JFrameMensalidades() {
        initComponents();
    }
    public JFrameMensalidades(JFramePrincipal jfP) {
        initComponents();
        jDBQueryMensallidade.setJDBConnection(jfP.getJDBConnection());
        jDBQueryMensallidade.execQuery();
        this.jfP=jfP;
    }
    public JFrameMensalidades(JFramePrincipal jfP, String mensalidadeId) {
        initComponents();
        jDBQueryMensallidade.setJDBConnection(jfP.getJDBConnection());
        jDBQueryMensallidade.execQuery();
        jDBQueryMensallidade.locate("id", mensalidadeId, true);
        this.jfP=jfP;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDBQueryMensallidade = new lib.jdb.jdbquery.JDBQuery();
        jDBControlStyle1 = new lib.jdb.control.jdbcontrolstyle.JDBControlStyle();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jDBTable9 = new lib.jdb.control.jdbtable.JDBTable();
        jButtonGerarMensalidades = new javax.swing.JButton();
        jButtonPassageiro = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jDBTextField31 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel41 = new javax.swing.JLabel();
        jDBTextField32 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel43 = new javax.swing.JLabel();
        jDBTextField33 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel44 = new javax.swing.JLabel();
        jDBTextField34 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jDBButtonSave10 = new lib.jdb.control.jdbbuttonsave.JDBButtonSave();
        jComboBoxSituacaoMensalidade = new javax.swing.JComboBox();
        jComboBoxmeses = new javax.swing.JComboBox();
        jLabelRecebido = new javax.swing.JLabel();
        jLabelAReceber = new javax.swing.JLabel();
        jLabelMensalidadesTotal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel45 = new javax.swing.JLabel();
        jDBTextField35 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel46 = new javax.swing.JLabel();
        jDBTextArea1 = new lib.jdb.control.jdbtextarea.JDBTextArea();

        jDBQueryMensallidade.setSQL("select * from mensalidade");
        jDBQueryMensallidade.addExecQueryEventListener(new lib.jdb.jdbquery.event.ExecQueryEventListener() {
            public void beforeExecQuery(lib.jdb.jdbquery.event.ExecQueryEventObject evt) {
            }
            public void afterExecQuery(lib.jdb.jdbquery.event.ExecQueryEventObject evt) {
                jDBQueryMensallidadeAfterExecQuery(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mensalidades");

        jDBTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jDBTable9.setJDBQuery(jDBQueryMensallidade);
        jDBTable9.setEditable(false);
        jDBTable9.setInvisibleFields("passageiro_id");
        jScrollPane10.setViewportView(jDBTable9);

        jButtonGerarMensalidades.setText("Gerar Mensalidades Mês Atual");
        jButtonGerarMensalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarMensalidadesActionPerformed(evt);
            }
        });

        jButtonPassageiro.setText("Passageiro");
        jButtonPassageiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPassageiroActionPerformed(evt);
            }
        });

        jLabel36.setText("Vencimento");

        jDBTextField31.setJDBQuery(jDBQueryMensallidade);
        jDBTextField31.setFieldName("vencimento");
        jDBTextField31.setjDBControlStyle(jDBControlStyle1);

        jLabel41.setText("Valor");

        jDBTextField32.setJDBQuery(jDBQueryMensallidade);
        jDBTextField32.setFieldName("valor");
        jDBTextField32.setjDBControlStyle(jDBControlStyle1);

        jLabel43.setText("Recebido em");

        jDBTextField33.setJDBQuery(jDBQueryMensallidade);
        jDBTextField33.setFieldName("recebido_em");
        jDBTextField33.setjDBControlStyle(jDBControlStyle1);

        jLabel44.setText("Valor Recebido");

        jDBTextField34.setJDBQuery(jDBQueryMensallidade);
        jDBTextField34.setFieldName("valor_recebido");
        jDBTextField34.setjDBControlStyle(jDBControlStyle1);

        jDBButtonSave10.setJDBQuery(jDBQueryMensallidade);

        jComboBoxSituacaoMensalidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todas", "Pagas", "Abertas" }));
        jComboBoxSituacaoMensalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSituacaoMensalidadeActionPerformed(evt);
            }
        });

        jComboBoxmeses.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Fevereiro", "Março", "Abril", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro" }));
        jComboBoxmeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxmesesActionPerformed(evt);
            }
        });

        jLabelRecebido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelRecebido.setText("Total Recebido R$ ##,##");

        jLabelAReceber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAReceber.setText("Total à Receber R$ ##,##");

        jLabelMensalidadesTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelMensalidadesTotal.setText("De R$ ##,## | x faturas");

        jLabel45.setText("Desconto");

        jDBTextField35.setJDBQuery(jDBQueryMensallidade);
        jDBTextField35.setFieldName("desconto");
        jDBTextField35.setjDBControlStyle(jDBControlStyle1);

        jLabel46.setText("Obs.");

        jDBTextArea1.setJDBQuery(jDBQueryMensallidade);
        jDBTextArea1.setFieldName("obs");
        jDBTextArea1.setjDBControlStyle(jDBControlStyle1);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jButtonGerarMensalidades)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addComponent(jButtonPassageiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxmeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxSituacaoMensalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelRecebido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelAReceber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                                    .addComponent(jLabelMensalidadesTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jDBButtonSave10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel43)
                            .addComponent(jLabel41)
                            .addComponent(jLabel36)
                            .addComponent(jLabel44)
                            .addComponent(jLabel45)
                            .addComponent(jLabel46))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDBTextArea1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jDBTextField32, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(jDBTextField31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDBTextField33, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDBTextField34, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDBTextField35, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGerarMensalidades)
                    .addComponent(jButtonPassageiro)
                    .addComponent(jComboBoxSituacaoMensalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxmeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jDBTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRecebido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAReceber)
                    .addComponent(jDBTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel43)
                        .addComponent(jDBTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMensalidadesTotal)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(jDBTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel45)
                            .addComponent(jDBTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jDBTextArea1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDBButtonSave10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 11, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGerarMensalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarMensalidadesActionPerformed
       /* jDBQueryPassageiros.first();
        int n = 0;
        do{
            String data = Calendar.getInstance().getTime().toLocaleString().split(" ")[0];
            jDBQueryMensallidade.setSQL("select * from mensalidade where passageiro_id = "+
                jDBQueryPassageiros.getCurrentFieldValue("id")+
                " and month(vencimento) = month(curdate()) and year(vencimento) = year(curdate())");
            jDBQueryMensallidade.execQuery();
            if(jDBQueryMensallidade.getQueryQuantity() == 1 ||
                jDBQueryPassageiros.getCurrentFieldValueAsString("Classificação").equals("S")) continue;
            jDBQuerySlavePassageiroMensalidades.insert();
            jDBQuerySlavePassageiroMensalidades.setNewCurrentFieldValue("passageiro_id", jDBQueryPassageiros.getCurrentFieldValue("id"));
            float valorMensalidade = (jDBQueryPassageiros.getCurrentFieldValueAsBoolean("vai") ?
                jDBQueryConfig.getCurrentFieldValueAsFloat("mensalidade")/2 : 0) +
            (jDBQueryPassageiros.getCurrentFieldValueAsBoolean("volta") ?
                jDBQueryConfig.getCurrentFieldValueAsFloat("mensalidade")/2 : 0);

            jDBQuerySlavePassageiroMensalidades.setNewCurrentFieldValueAsFloat("valor", valorMensalidade );
            jDBQuerySlavePassageiroMensalidades.setNewCurrentFieldValue("vencimento", "10/"+
                data.split("/")[1]+"/"+data.split("/")[2]);

            jDBQuerySlavePassageiroMensalidades.save();
            n++;
        }while(jDBQueryPassageiros.next()>0);
        jDBQueryMensallidade.setSQL("select * from mensalidade");
        jDBQueryMensallidade.execQuery();
        JOptionPane.showMessageDialog(null, "Foram geradas "+n+" mensalidades.");
        */
    }//GEN-LAST:event_jButtonGerarMensalidadesActionPerformed

    private void jButtonPassageiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPassageiroActionPerformed
        jfP.JFramePassageiros(jDBQueryMensallidade.getCurrentFieldValueAsInteger("passageiro_id"));
    }//GEN-LAST:event_jButtonPassageiroActionPerformed

    private void jComboBoxSituacaoMensalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSituacaoMensalidadeActionPerformed
        updateQryMensalidade();
    }//GEN-LAST:event_jComboBoxSituacaoMensalidadeActionPerformed

    private void jComboBoxmesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxmesesActionPerformed
        updateQryMensalidade();
    }//GEN-LAST:event_jComboBoxmesesActionPerformed

    
    private void updateQryMensalidade(){
        String sql = SQLMensalidade;
         if(jComboBoxmeses.getSelectedIndex() > 0)
            sql += " and month(vencimento)="+(jComboBoxmeses.getSelectedIndex()+1);
         switch(jComboBoxSituacaoMensalidade.getSelectedItem().toString()){
             case "Pagas":
                 sql += " and recebido_em is not null";
                 break;
             case "Abertas":
                 sql += " and recebido_em is null";
                 break;
                 default: break;
         }
         jDBQueryMensallidade.setSQL(sql);
         jDBQueryMensallidade.execQuery();
    }
    
    private void jDBQueryMensallidadeAfterExecQuery(lib.jdb.jdbquery.event.ExecQueryEventObject evt) {//GEN-FIRST:event_jDBQueryMensallidadeAfterExecQuery
        float pago = 0, pendente = 0, total = 0;
        int qtd = 0, qtdPend = 0;
        jDBQueryMensallidade.first();
        if(jDBQueryMensallidade.getRows().size()>0){
            do{
                if(jDBQueryMensallidade.getCurrentFieldValueAsFloat("valor_recebido")==0){
                    pendente += jDBQueryMensallidade.getCurrentFieldValueAsFloat("valor");
                    qtdPend++;
                }else pago += jDBQueryMensallidade.getCurrentFieldValueAsFloat("valor_recebido");
                total +=  jDBQueryMensallidade.getCurrentFieldValueAsFloat("valor");
                qtd++;
            }while(jDBQueryMensallidade.next()>=1);
        }
        jDBQueryMensallidade.first();
        jLabelAReceber.setText(String.format("Total à Receber R$ %.2f | %d mesalidades", pendente,qtdPend));
        jLabelRecebido.setText(String.format("Total Recebido R$ %.2f | %d mesalidades", pago, qtd-qtdPend));
        jLabelMensalidadesTotal.setText(String.format("De R$ %.2f | %d mesalidades.",total,qtd));
    }//GEN-LAST:event_jDBQueryMensallidadeAfterExecQuery

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMensalidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMensalidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMensalidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMensalidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMensalidades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGerarMensalidades;
    private javax.swing.JButton jButtonPassageiro;
    private javax.swing.JComboBox jComboBoxSituacaoMensalidade;
    private javax.swing.JComboBox jComboBoxmeses;
    private lib.jdb.control.jdbbuttonsave.JDBButtonSave jDBButtonSave10;
    private lib.jdb.control.jdbcontrolstyle.JDBControlStyle jDBControlStyle1;
    private lib.jdb.jdbquery.JDBQuery jDBQueryMensallidade;
    private lib.jdb.control.jdbtable.JDBTable jDBTable9;
    private lib.jdb.control.jdbtextarea.JDBTextArea jDBTextArea1;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField31;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField32;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField33;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField34;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabelAReceber;
    private javax.swing.JLabel jLabelMensalidadesTotal;
    private javax.swing.JLabel jLabelRecebido;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
