
import lib.jdb.connection.JDBConnection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vmf
 */
public class JFrameDespesas extends javax.swing.JFrame {
    String SQLMensalidade = "select * from mensalidade where 1=1 ",
            SQLDespesa = "select * from despesa where 1=1 ";
    /**
     * Creates new form JFrameDespesas
     */
    public JFrameDespesas() {
        initComponents();
    }
    public JFrameDespesas(JDBConnection jdbc) {
       this();
       jDBQueryMensallidade.setJDBConnection(jdbc);
       jDBQueryMensallidade.execQuery();
       jDBQueryDespesas.setJDBConnection(jdbc);
       jDBQueryDespesas.execQuery();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDBQueryMensallidade = new lib.jdb.jdbquery.JDBQuery();
        jDBControlStyle1 = new lib.jdb.control.jdbcontrolstyle.JDBControlStyle();
        jDBQueryDespesas = new lib.jdb.jdbquery.JDBQuery();
        jScrollPane9 = new javax.swing.JScrollPane();
        jDBTable8 = new lib.jdb.control.jdbtable.JDBTable();
        jDBButtonNew6 = new lib.jdb.control.jdbbuttonnew.JDBButtonNew();
        jDBButtonSave9 = new lib.jdb.control.jdbbuttonsave.JDBButtonSave();
        jDBButtonDelete6 = new lib.jdb.control.jdbbuttondelete.JDBButtonDelete();
        jLabel40 = new javax.swing.JLabel();
        jDBTextField29 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jDBTextField35 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jDBTextArea2 = new lib.jdb.control.jdbtextarea.JDBTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelTotalDespesas = new javax.swing.JLabel();
        jLabelBalncoMensal = new javax.swing.JLabel();
        jLabelBalancoEntradas = new javax.swing.JLabel();
        jComboBoxBalancoMeses = new javax.swing.JComboBox();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelBalancoEntradas1 = new javax.swing.JLabel();
        jLabelTotalDespesas1 = new javax.swing.JLabel();
        jLabelBalancoEntradasQtd = new javax.swing.JLabel();
        jLabelTotalDespesasQtd = new javax.swing.JLabel();
        jLabelBalance2 = new javax.swing.JLabel();
        jLabelBalanco = new javax.swing.JLabel();

        jDBQueryMensallidade.setSQL("select * from mensalidade");
        jDBQueryMensallidade.addExecQueryEventListener(new lib.jdb.jdbquery.event.ExecQueryEventListener() {
            public void beforeExecQuery(lib.jdb.jdbquery.event.ExecQueryEventObject evt) {
            }
            public void afterExecQuery(lib.jdb.jdbquery.event.ExecQueryEventObject evt) {
                jDBQueryMensallidadeAfterExecQuery(evt);
            }
        });

        jDBQueryDespesas.setSQL("select * from despesa");
        jDBQueryDespesas.addExecQueryEventListener(new lib.jdb.jdbquery.event.ExecQueryEventListener() {
            public void beforeExecQuery(lib.jdb.jdbquery.event.ExecQueryEventObject evt) {
            }
            public void afterExecQuery(lib.jdb.jdbquery.event.ExecQueryEventObject evt) {
                jDBQueryDespesasAfterExecQuery(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Despesas");

        jDBTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jDBTable8.setJDBQuery(jDBQueryDespesas);
        jDBTable8.setEditable(false);
        jDBTable8.setInvisibleFields("id ");
        jScrollPane9.setViewportView(jDBTable8);

        jDBButtonNew6.setJDBQuery(jDBQueryDespesas);

        jDBButtonSave9.setJDBQuery(jDBQueryDespesas);

        jDBButtonDelete6.setJDBQuery(jDBQueryDespesas);

        jLabel40.setText("Data");

        jDBTextField29.setJDBQuery(jDBQueryDespesas);
        jDBTextField29.setFieldName("data");
        jDBTextField29.setjDBControlStyle(jDBControlStyle1);

        jDBTextField35.setJDBQuery(jDBQueryDespesas);
        jDBTextField35.setFieldName("valor");
        jDBTextField35.setjDBControlStyle(jDBControlStyle1);

        jLabel45.setText("Valor");

        jLabel46.setText("Resumo");

        jDBTextArea2.setJDBQuery(jDBQueryDespesas);
        jDBTextArea2.setFieldName("resumo");
        jDBTextArea2.setjDBControlStyle(jDBControlStyle1);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelTotalDespesas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTotalDespesas.setForeground(new java.awt.Color(204, 0, 0));
        jLabelTotalDespesas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTotalDespesas.setText("Total R$ ##,##");

        jLabelBalncoMensal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelBalncoMensal.setText("Balanço Mensal");

        jLabelBalancoEntradas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelBalancoEntradas.setForeground(new java.awt.Color(0, 0, 255));
        jLabelBalancoEntradas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelBalancoEntradas.setText("Total R$ ##,##");

        jComboBoxBalancoMeses.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Fevereiro", "Março", "Abril", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro" }));
        jComboBoxBalancoMeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBalancoMesesActionPerformed(evt);
            }
        });

        jLabelBalancoEntradas1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelBalancoEntradas1.setForeground(new java.awt.Color(0, 0, 255));
        jLabelBalancoEntradas1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelBalancoEntradas1.setText("RECEBIDO");

        jLabelTotalDespesas1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTotalDespesas1.setForeground(new java.awt.Color(204, 0, 0));
        jLabelTotalDespesas1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTotalDespesas1.setText("PAGO");

        jLabelBalancoEntradasQtd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelBalancoEntradasQtd.setForeground(new java.awt.Color(0, 0, 255));
        jLabelBalancoEntradasQtd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelBalancoEntradasQtd.setText("x mensalidades");

        jLabelTotalDespesasQtd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTotalDespesasQtd.setForeground(new java.awt.Color(204, 0, 0));
        jLabelTotalDespesasQtd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTotalDespesasQtd.setText("x contas");

        jLabelBalance2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelBalance2.setForeground(new java.awt.Color(102, 153, 0));
        jLabelBalance2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelBalance2.setText("TOTAL");

        jLabelBalanco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelBalanco.setForeground(new java.awt.Color(102, 153, 0));
        jLabelBalanco.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelBalanco.setText("TOTAL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDBTextArea2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(54, 54, 54)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel45)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jDBTextField35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel40)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jDBTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jDBButtonDelete6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jDBButtonNew6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jDBButtonSave9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                                .addComponent(jLabelBalncoMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxBalancoMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelTotalDespesas1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelBalancoEntradas1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelTotalDespesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelBalancoEntradas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabelTotalDespesasQtd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelBalancoEntradasQtd, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelBalance2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelBalanco, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addComponent(jScrollPane9))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBalncoMensal)
                            .addComponent(jComboBoxBalancoMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelBalancoEntradas1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelTotalDespesas1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelBalancoEntradas)
                                    .addComponent(jLabelBalancoEntradasQtd))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelTotalDespesas)
                                    .addComponent(jLabelTotalDespesasQtd))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBalance2)
                            .addComponent(jLabelBalanco))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDBTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDBTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel45))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel46)
                            .addComponent(jDBTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDBButtonDelete6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDBButtonNew6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDBButtonSave9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxBalancoMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBalancoMesesActionPerformed
        String sql = SQLDespesa, sqlM = SQLMensalidade;;
        if(jComboBoxBalancoMeses.getSelectedIndex() > 0){
            sql += " and month(data)="+(jComboBoxBalancoMeses.getSelectedIndex()+1);
            sqlM += " and month(recebido_em)="+(jComboBoxBalancoMeses.getSelectedIndex()+1);
        }
        jDBQueryMensallidade.setSQL(sqlM);
        jDBQueryMensallidade.execQuery();
        jDBQueryDespesas.setSQL(sql);
        jDBQueryDespesas.execQuery();
    }//GEN-LAST:event_jComboBoxBalancoMesesActionPerformed

    private void jDBQueryMensallidadeAfterExecQuery(lib.jdb.jdbquery.event.ExecQueryEventObject evt) {//GEN-FIRST:event_jDBQueryMensallidadeAfterExecQuery

    }//GEN-LAST:event_jDBQueryMensallidadeAfterExecQuery

    private void jDBQueryDespesasAfterExecQuery(lib.jdb.jdbquery.event.ExecQueryEventObject evt) {//GEN-FIRST:event_jDBQueryDespesasAfterExecQuery
        float pago = 0, recebido = 0, balanco = 0;
        int qtdRecebido = 0, qtdpago = 0;
        jDBQueryMensallidade.first();
        if(jDBQueryMensallidade.getRow()>0){
            do{
                if(jDBQueryMensallidade.getCurrentFieldValueAsFloat("valor_recebido")>0){
                    recebido += jDBQueryMensallidade.getCurrentFieldValueAsFloat("valor_recebido");
                    qtdRecebido++;
                }
            }while(jDBQueryMensallidade.next()>=1);
        }
        if(jDBQueryDespesas.getRow()>0){
            do{
                pago +=  jDBQueryDespesas.getCurrentFieldValueAsFloat("valor");
                qtdpago++;
            }while(jDBQueryDespesas.next()>=1);
        }
        jDBQueryDespesas.first();
        jLabelTotalDespesas.setText(String.format("R$ %.2f", pago));
        jLabelTotalDespesasQtd.setText(String.format("%d registros", qtdpago));
        jDBQueryMensallidade.first();
        jLabelBalancoEntradas.setText(String.format("R$ %.2f", recebido));
        jLabelBalancoEntradasQtd.setText(String.format("%d mesalidades", qtdRecebido));
        balanco = recebido - pago;
        if(balanco < 0){
            jLabelBalance2.setForeground(jLabelTotalDespesas.getForeground());
            jLabelBalanco.setForeground(jLabelTotalDespesas.getForeground());
        }else{
            jLabelBalance2.setForeground(jLabelBalancoEntradas.getForeground());
            jLabelBalanco.setForeground(jLabelBalancoEntradas.getForeground());
        }
        jLabelBalanco.setText(String.format("R$ %.2f", balanco));
    }//GEN-LAST:event_jDBQueryDespesasAfterExecQuery

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameDespesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxBalancoMeses;
    private lib.jdb.control.jdbbuttondelete.JDBButtonDelete jDBButtonDelete6;
    private lib.jdb.control.jdbbuttonnew.JDBButtonNew jDBButtonNew6;
    private lib.jdb.control.jdbbuttonsave.JDBButtonSave jDBButtonSave9;
    private lib.jdb.control.jdbcontrolstyle.JDBControlStyle jDBControlStyle1;
    private lib.jdb.jdbquery.JDBQuery jDBQueryDespesas;
    private lib.jdb.jdbquery.JDBQuery jDBQueryMensallidade;
    private lib.jdb.control.jdbtable.JDBTable jDBTable8;
    private lib.jdb.control.jdbtextarea.JDBTextArea jDBTextArea2;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField29;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField35;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabelBalance2;
    private javax.swing.JLabel jLabelBalanco;
    private javax.swing.JLabel jLabelBalancoEntradas;
    private javax.swing.JLabel jLabelBalancoEntradas1;
    private javax.swing.JLabel jLabelBalancoEntradasQtd;
    private javax.swing.JLabel jLabelBalncoMensal;
    private javax.swing.JLabel jLabelTotalDespesas;
    private javax.swing.JLabel jLabelTotalDespesas1;
    private javax.swing.JLabel jLabelTotalDespesasQtd;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
